---
name: auto-testing
on:
  - push
jobs:
  build:
    #runs-on: [ubuntu-latest]
    runs-on: self-hosted
    #container: docker://dvcorg/cml-py3:latest
    steps:
#       - name: Checkout rotx-maxim/ai8x-training
#         uses: actions/checkout@v2
#         with:
#           repository: rotx-maxim/ai8x-training
#           ref: pytorch-2.0
#           submodules: recursive
      - name: Checkout MaximIntegratedAI/ai8x-training
        uses: actions/checkout@v2
        with:
          repository: MaximIntegratedAI/ai8x-training
          ref: pytorch-2.0
          submodules: recursive         
      - name: Checkout Test Codes
        uses: actions/checkout@v2
        with:
          repository: asyatrhl/ai8x-training-test-codes
          ref: main
          path: test_codes
      - name: Checkout Test Codes
        uses: actions/checkout@v2
        with:
          repository: asyatrhl/regression-test
          ref: main
          path: last-dev
      - name: Setup Pyenv and Install Dependencies
        uses: gabrielfalcao/pyenv-action@v13
        with:
          default: 3.8.11
      - name: Create Venv
        run: pyenv local 3.8.11 & python3 -m venv venv --prompt ai8x-training
      - name: Activate Venv
        run: source venv/bin/activate
      - name: Install Dependencies
        run: pip3 install -U pip wheel setuptools && pip3 install -r
          ./test_codes/requirements-cu11.txt
      - name: Install Facenet-pytorch
        run: pip install facenet-pytorch
      - name: Check Pytorch version
        run: pip list | grep torch
      - name: installnumpy 1.22.4
        run: pip install numpy==1.22.4
      - name: Check Numpy version
        run: pip show numpy --version
      - name: Last Develop Check
        run: python ./test_codes/last_dev.py --testconf ./last-dev/test_config.yaml
#       - name: deneme
#         run:  python train.py --cpu --deterministic --print-freq 200 --epochs 1 --optimizer Adam --lr 0.001 --wd 0 --model ai85tinierssd --use-bias --momentum 0.9 --weight-decay 5e-4 --dataset SVHN_74 --device MAX78000 --obj-detection --obj-detection-params parameters/obj_detection_params_svhn.yaml --batch-size 16 --qat-policy policies/qat_policy_svhn.yaml --validation-split 0 --name ai85tinierssd-SVHN_74 --data /data_ssd "$@" 
      - name: deneme
        run:  python train.py --deterministic --pr-curves --epochs 1 --optimizer Adam --lr 0.001 --wd 0 --model ai85unetlarge --out-fold-ratio 4 --use-bias --dataset AISegment_352 --device MAX78000 --batch-size 32 --qat-policy policies/qat_policy_aisegment.yaml --compress policies/schedule-aisegment.yaml --validation-split 0 --print-freq 250 --name ai85unetlarge-AISegment_352 --data /data_ssd "$@" 
      - name: Create Test Script
        run: python ./test_codes/create_test_script.py --testconf ./last-dev/test_config.yaml
#       - name: Run Training Scripts
#         run: bash
#           /home/asyaturhal/desktop/ai/test_scripts/output_file.sh
      - name: Save Log Files
        run: cp -r
          /home/asyaturhal/actions-runner/_work/ai8x-training/ai8x-training/logs/
          /home/asyaturhal/desktop/ai/test_logs/$(date +"%Y-%m-%d-%k-%M-")
      - name: Log Diff
        run: python ./test_codes/log_comparison.py
      - name: Test Results
        run: python ./test_codes/pass_fail.py --testconf ./last-dev/test_config.yaml
      - name: Create ONNX script
        run: python ./test_codes/create_onnx_scripts.py --testconf ./last-dev/test_config.yaml
      - name: Run ONNX
        run: bash
          /home/asyaturhal/actions-runner/_work/ai8x-training/ai8x-training/scripts/onnx_scripts.sh
